# firewall configuration
#
#
---

- name: stop and disable firewalld
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Fedora' shorewall.install == true
  service:
    name: firewalld
    enabled: no
    state: stopped
  tags: [firewall]
  failed_when: false
  changed_when: false

- name: uninstall firewalld
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Fedora' shorewall.install == true
  package:
    name: firewalld
    state: absent
  tags: [firewall]

- name: install shorewall
  package:
    name:
      - shorewall
    state: present
  when: shorewall.install == true
  tags: [firewall]

- name: install shorewall6
  package:
    name:
      - shorewall6
    state: present
  when: shorewall6.install == true
  tags: [firewall]

- name: update firewall configuration
  template:
    src: "shorewall/{{ item }}.j2"
    dest: "/etc/shorewall/{{ item }}"
    owner: root
    group: root
    mode: '600'
  with_items: "{{ shorewall_configfiles }}"
  tags: [firewall]
  when: shorewall_configfiles is defined
  register: shorewallconfig
  notify: restart shorewall

- name: update firewall6 configuration
  template:
    src: "shorewall6/{{ item }}.j2"
    dest: "/etc/shorewall6/{{ item }}"
    owner: root
    group: root
    mode: '600'
  with_items: "{{ shorewall6_configfiles }}"
  tags: [firewall]
  when: shorewall6_configfiles is defined
  register: shorewall6config
  notify: restart shorewall6

- name: enable shorewall service
  service:
    name: shorewall
    state: started
    enabled: yes
  when: shorewallconfig.changed and shorewall.service == true

- name: enable shorewall6 service
  service:
    name: shorewall6
    state: started
    enabled: yes
  when: shorewall6config.changed and shorewall.service == true
...
